import QtQuick
import QtQuick.Controls
import Quickshell
import Quickshell.Io
import qs.Ui
import qs.Commons
import "Model.js" as Model

Panel {
  id: root
  moduleName: "awkent01.touchpad"
  ipcTarget: "awkent01.touchpad"
  manageIpc: false

  // ---- State ----
  property string deviceName: ""
  property bool touchpadEnabled: true
  property bool naturalScroll: false
  property bool tapToClick: true
  property bool disableWhileTyping: true
  property bool clickfingerBehavior: true
  property real scrollFactor: 0.4

  // Pending scroll factor while dragging the slider.
  property real pendingScrollFactor: 0.4
  property bool scrollSetQueued: false

  // Carry sub-notch touchpad deltas between wheel events.
  property real wheelAccumulator: 0

  // ---- Cursor navigation ----
  // Sections: "header" (enable/disable toggle), "scroll" (scroll speed slider),
  // then toggle rows: "natural", "tap", "typing", "clickfinger"
  property string focusSection: "header"
  property int selectedIndex: 0
  property bool cursorActive: false

  readonly property var allSections: ["header", "scroll", "natural", "tap", "typing", "clickfinger"]

  readonly property string icon: {
    if (!deviceName) return ""
    return touchpadEnabled ? "󰟸" : "󰤳"
  }

  readonly property string heroStatusText: {
    if (!deviceName) return "NO DEVICE"
    return touchpadEnabled ? "ENABLED" : "DISABLED"
  }

  readonly property color hoverFill: bar
    ? Style.hoverFillFor(bar.foreground, Color.accent)
    : "transparent"
  readonly property color selectedFill: bar
    ? Style.selectedFillFor(bar.foreground, Color.accent)
    : "transparent"

  function moveCursor(delta) {
    var sections = allSections
    var sIdx = sections.indexOf(focusSection)
    if (sIdx < 0) { focusSection = sections[0]; return }

    if (delta > 0) {
      if (sIdx < sections.length - 1) focusSection = sections[sIdx + 1]
    } else {
      if (sIdx > 0) focusSection = sections[sIdx - 1]
    }
  }

  function moveCursorH(delta) {
    if (focusSection === "scroll") {
      adjustScrollFactor(delta > 0 ? 0.1 : -0.1)
    }
  }

  function activateCursor() {
    if (focusSection === "header") { toggleTouchpad(); return }
    if (focusSection === "natural") { toggleNaturalScroll(); return }
    if (focusSection === "tap") { toggleTapToClick(); return }
    if (focusSection === "typing") { toggleDisableWhileTyping(); return }
    if (focusSection === "clickfinger") { toggleClickfingerBehavior(); return }
  }

  // ---- Actions ----
  function toggleTouchpad() {
    if (!deviceName) return
    var next = !touchpadEnabled
    touchpadEnabled = next
    Quickshell.execDetached(["omarchy-toggle-input-device", "touchpad", next ? "on" : "off"])
  }

  function toggleNaturalScroll() {
    var next = !naturalScroll
    naturalScroll = next
    setHyprOption("natural_scroll", next)
  }

  function toggleTapToClick() {
    var next = !tapToClick
    tapToClick = next
    setHyprOption("tap_to_click", next)
  }

  function toggleDisableWhileTyping() {
    var next = !disableWhileTyping
    disableWhileTyping = next
    setHyprOption("disable_while_typing", next)
  }

  function toggleClickfingerBehavior() {
    var next = !clickfingerBehavior
    clickfingerBehavior = next
    setHyprOption("clickfinger_behavior", next)
  }

  function setHyprOption(option, value) {
    var luaValue = typeof value === "boolean" ? (value ? "true" : "false") : String(value)
    Quickshell.execDetached(["hyprctl", "eval", "hl.config({ input = { touchpad = { " + option + " = " + luaValue + " } } })"])
    persistSettings()
  }

  // `hyprctl eval` only changes the running compositor. Omarchy's default
  // input.lua hardcodes natural_scroll = false, so the next config reload
  // (theme switch, saving any hypr/*.lua, hyprctl reload) re-applies the
  // default and our runtime change is lost. Mirror every setting into the
  // toggles state dir, which default/hypr/toggles.lua re-requires on each
  // reload -- and does so after hypr/input.lua, so it wins.
  function persistSettings() {
    var lua = "-- Generated by the awkent01.touchpad bar widget. Edit the widget, not this file.\n"
      + "-- Loaded on every Hyprland config reload by default/hypr/toggles.lua, which is\n"
      + "-- what keeps these from reverting to Omarchy's input.lua defaults.\n"
      + "hl.config({\n"
      + "  input = {\n"
      + "    touchpad = {\n"
      + "      natural_scroll = " + (naturalScroll ? "true" : "false") + ",\n"
      + "      tap_to_click = " + (tapToClick ? "true" : "false") + ",\n"
      + "      disable_while_typing = " + (disableWhileTyping ? "true" : "false") + ",\n"
      + "      clickfinger_behavior = " + (clickfingerBehavior ? "true" : "false") + ",\n"
      + "      scroll_factor = " + Model.clampScrollFactor(scrollFactor).toFixed(1) + ",\n"
      + "    },\n"
      + "  },\n"
      + "})\n"

    // Only booleans and a clamped number reach the file -- no device names or
    // other outside strings are ever interpolated into generated Lua.
    Quickshell.execDetached(["bash", "-c",
      "dir=\"$HOME/.local/state/omarchy/toggles/hypr\"; mkdir -p \"$dir\" && " +
      "cat > \"$dir/touchpad-settings.lua\" <<'OMARCHY_TOUCHPAD_EOF'\n" + lua + "OMARCHY_TOUCHPAD_EOF\n"])
  }

  function adjustScrollFactor(delta) {
    var next = Model.clampScrollFactor(scrollFactor + delta)
    scrollFactor = next
    pendingScrollFactor = next
    scrollDebounce.restart()
  }

  function setScrollFactor(value) {
    var clamped = Model.clampScrollFactor(value)
    scrollFactor = clamped
    pendingScrollFactor = clamped
    scrollDebounce.restart()
  }

  function commitScrollFactor() {
    setHyprOption("scroll_factor", pendingScrollFactor)
  }

  function refresh() {
    if (!stateProc.running) stateProc.running = true
  }

  // ---- IPC ----
  IpcHandler {
    target: "awkent01.touchpad"

    function open() { root.open() }
    function close() { root.close() }
    function toggle() { root.toggle() }
    function show() { root.open() }
    function hide() { root.close() }
  }

  // ---- Lifecycle ----
  visible: deviceName !== ""
  implicitWidth: button.implicitWidth
  implicitHeight: button.implicitHeight

  Component.onCompleted: refresh()

  onOpenedChanged: {
    if (opened) {
      refresh()
      focusSection = "header"
      cursorActive = false
    }
  }

  // Poll while open so external changes are reflected.
  Timer {
    interval: 3000
    running: root.opened
    repeat: true
    onTriggered: root.refresh()
  }

  Timer {
    id: scrollDebounce
    interval: 200
    repeat: false
    onTriggered: root.commitScrollFactor()
  }

  // ---- State process: reads all touchpad options in one shot ----
  Process {
    id: stateProc
    command: ["bash", "-c",
      "hyprctl devices -j 2>/dev/null; echo '---SPLIT---'; " +
      "hyprctl getoption input:touchpad:natural_scroll -j 2>/dev/null; echo '---SPLIT---'; " +
      "hyprctl getoption input:touchpad:scroll_factor -j 2>/dev/null; echo '---SPLIT---'; " +
      "hyprctl getoption 'input:touchpad:tap-to-click' -j 2>/dev/null; echo '---SPLIT---'; " +
      "hyprctl getoption input:touchpad:disable_while_typing -j 2>/dev/null; echo '---SPLIT---'; " +
      "hyprctl getoption input:touchpad:clickfinger_behavior -j 2>/dev/null; echo '---SPLIT---'; " +
      "test -f \"$HOME/.local/state/omarchy/toggles/hypr/touchpad-disabled-name\" && echo disabled || echo enabled"
    ]
    stdout: StdioCollector {
      waitForEnd: true
      onStreamFinished: {
        var parts = String(text || "").split("---SPLIT---")
        if (parts.length < 7) return

        root.deviceName = Model.parseTouchpadDevice(parts[0])
        root.naturalScroll = Model.parseBool(parts[1])
        root.scrollFactor = Model.parseFloat(parts[2]) || 0.4
        root.pendingScrollFactor = root.scrollFactor
        root.tapToClick = Model.parseBool(parts[3])
        root.disableWhileTyping = Model.parseBool(parts[4])
        root.clickfingerBehavior = Model.parseBool(parts[5])
        root.touchpadEnabled = String(parts[6] || "").trim() !== "disabled"
      }
    }
  }

  // ---- Bar icon ----
  BarIconButton {
    id: button
    anchors.fill: parent
    bar: root.bar
    text: root.icon
    onPressed: function(b) {
      if (b === Qt.RightButton) root.toggleTouchpad()
      else root.toggle()
    }
  }

  // ---- Popup panel ----
  KeyboardPanel {
    id: panel
    anchorItem: button
    owner: root
    bar: root.bar
    open: root.opened
    focusTarget: keyCatcher
    contentWidth: panel.fittedContentWidth(Style.space(340))
    contentHeight: panel.fittedContentHeight(column.implicitHeight)

    PanelKeyCatcher {
      id: keyCatcher
      anchors.fill: parent
      onMoveRequested: function(dx, dy) {
        if (!root.cursorActive) { root.cursorActive = true; return }
        if (dy !== 0) root.moveCursor(dy)
        else if (dx !== 0) root.moveCursorH(dx)
      }
      onActivateRequested: if (root.cursorActive) root.activateCursor()
      onCloseRequested: root.close()
      onTabRequested: function(direction) { root.switchPanel(direction) }

      Column {
        id: column
        anchors.fill: parent
        spacing: Style.space(14)

        // ========== Hero: Touchpad icon + status + power toggle ==========
        Item {
          width: parent.width
          implicitHeight: Math.max(heroIcon.implicitHeight, heroLabels.implicitHeight, powerSwitch.implicitHeight)

          Text {
            id: heroIcon
            anchors.left: parent.left
            anchors.verticalCenter: parent.verticalCenter
            text: root.icon
            color: root.bar.foreground
            font.family: root.bar.fontFamily
            font.pixelSize: Style.font.display
            opacity: root.touchpadEnabled ? 1.0 : 0.5
          }

          ToggleSwitch {
            id: powerSwitch
            visible: root.deviceName !== ""
            checked: root.touchpadEnabled
            hasCursor: root.cursorActive && root.focusSection === "header"
            foreground: root.bar.foreground
            anchors.right: parent.right
            anchors.verticalCenter: parent.verticalCenter
            onHovered: function(on) {
              if (on) {
                root.cursorActive = true
                root.focusSection = "header"
              }
            }
            onToggled: root.toggleTouchpad()

            PanelToolTip {
              visible: powerSwitch.containsMouse
              text: root.touchpadEnabled ? "Disable touchpad" : "Enable touchpad"
              fontFamily: root.bar.fontFamily
            }
          }

          Column {
            id: heroLabels
            anchors.left: heroIcon.right
            anchors.leftMargin: Style.space(14)
            anchors.right: parent.right
            anchors.rightMargin: powerSwitch.visible ? powerSwitch.width + Style.space(12) : 0
            anchors.verticalCenter: parent.verticalCenter
            spacing: Style.space(2)

            Text {
              text: "Touchpad"
              color: root.bar.foreground
              font.family: root.bar.fontFamily
              font.pixelSize: Style.font.title
              font.bold: true
              elide: Text.ElideRight
              width: parent.width
            }

            Text {
              text: root.heroStatusText
              color: Qt.darker(root.bar.foreground, 1.4)
              font.family: root.bar.fontFamily
              font.pixelSize: Style.font.caption
              font.bold: true
              font.letterSpacing: 1.2
              elide: Text.ElideRight
              width: parent.width
            }
          }
        }

        PanelSeparator {
          foreground: root.bar.foreground
        }

        // ========== Scroll speed slider ==========
        Column {
          width: parent.width
          spacing: Style.space(8)
          opacity: root.touchpadEnabled ? 1.0 : 0.4

          Item {
            width: parent.width
            implicitHeight: scrollLabel.implicitHeight

            Text {
              id: scrollLabel
              anchors.left: parent.left
              anchors.verticalCenter: parent.verticalCenter
              text: "Scroll Speed"
              color: root.bar.foreground
              font.family: root.bar.fontFamily
              font.pixelSize: Style.font.body
            }

            Text {
              anchors.right: parent.right
              anchors.verticalCenter: parent.verticalCenter
              text: {
                var v = scrollSlider.dragging ? scrollSlider.liveValue : root.scrollFactor
                return Model.scrollSpeedLabel(v) + "  " + v.toFixed(1)
              }
              color: Qt.darker(root.bar.foreground, 1.4)
              font.family: root.bar.fontFamily
              font.pixelSize: Style.font.caption
            }
          }

          Item {
            width: parent.width
            implicitHeight: Math.max(minusBtn.implicitHeight, scrollRow.implicitHeight, plusBtn.implicitHeight)

            // Minus button
            CursorSurface {
              id: minusSurface
              anchors.left: parent.left
              anchors.verticalCenter: parent.verticalCenter
              width: Style.space(32)
              height: Style.space(32)
              hasCursor: false
              foreground: root.bar.foreground
              fill: root.hoverFill

              Text {
                id: minusBtn
                anchors.centerIn: parent
                text: "−"
                color: root.bar.foreground
                font.family: root.bar.fontFamily
                font.pixelSize: Style.font.heading
                opacity: root.scrollFactor <= 0.1 ? 0.3 : 1.0
              }

              MouseArea {
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: root.adjustScrollFactor(-0.1)
                onContainsMouseChanged: if (containsMouse) {
                  root.cursorActive = true
                  root.focusSection = "scroll"
                }
              }
            }

            // Slider track
            CursorSurface {
              id: scrollRow
              anchors.left: minusSurface.right
              anchors.right: plusSurface.left
              anchors.leftMargin: Style.space(4)
              anchors.rightMargin: Style.space(4)
              anchors.verticalCenter: parent.verticalCenter
              height: scrollSlider.implicitHeight + Style.spacing.controlGap
              hasCursor: root.cursorActive && root.focusSection === "scroll"
              foreground: root.bar.foreground
              outline: true

              PanelSlider {
                id: scrollSlider
                bar: root.bar
                anchors.fill: parent
                anchors.leftMargin: Style.space(6)
                anchors.rightMargin: Style.space(6)
                minimum: 0.1
                maximum: 2.0
                step: 0.1
                value: root.scrollFactor
                onMoved: function(v) { root.setScrollFactor(v) }
                onReleased: function(v) {
                  scrollDebounce.stop()
                  root.setScrollFactor(v)
                  root.commitScrollFactor()
                }
              }

              HoverHandler {
                onHoveredChanged: if (hovered) {
                  root.cursorActive = true
                  root.focusSection = "scroll"
                }
              }
            }

            // Plus button
            CursorSurface {
              id: plusSurface
              anchors.right: parent.right
              anchors.verticalCenter: parent.verticalCenter
              width: Style.space(32)
              height: Style.space(32)
              hasCursor: false
              foreground: root.bar.foreground
              fill: root.hoverFill

              Text {
                id: plusBtn
                anchors.centerIn: parent
                text: "+"
                color: root.bar.foreground
                font.family: root.bar.fontFamily
                font.pixelSize: Style.font.heading
                opacity: root.scrollFactor >= 2.0 ? 0.3 : 1.0
              }

              MouseArea {
                anchors.fill: parent
                hoverEnabled: true
                cursorShape: Qt.PointingHandCursor
                onClicked: root.adjustScrollFactor(0.1)
                onContainsMouseChanged: if (containsMouse) {
                  root.cursorActive = true
                  root.focusSection = "scroll"
                }
              }
            }
          }
        }

        PanelSeparator {
          foreground: root.bar.foreground
        }

        // ========== Toggle rows ==========
        Column {
          width: parent.width
          spacing: Style.space(6)
          opacity: root.touchpadEnabled ? 1.0 : 0.4

          ToggleRow {
            width: parent.width
            label: "Natural Scrolling"
            description: "Scroll content in the direction of finger movement"
            checked: root.naturalScroll
            sectionName: "natural"
            enabled: root.touchpadEnabled
            onToggled: root.toggleNaturalScroll()
          }

          ToggleRow {
            width: parent.width
            label: "Tap to Click"
            description: "Tap the touchpad to click"
            checked: root.tapToClick
            sectionName: "tap"
            enabled: root.touchpadEnabled
            onToggled: root.toggleTapToClick()
          }

          ToggleRow {
            width: parent.width
            label: "Disable While Typing"
            description: "Ignore touchpad input while typing"
            checked: root.disableWhileTyping
            sectionName: "typing"
            enabled: root.touchpadEnabled
            onToggled: root.toggleDisableWhileTyping()
          }

          ToggleRow {
            width: parent.width
            label: "Two-Finger Right Click"
            description: "Use two-finger tap for right-click"
            checked: root.clickfingerBehavior
            sectionName: "clickfinger"
            enabled: root.touchpadEnabled
            onToggled: root.toggleClickfingerBehavior()
          }
        }
      }
    }
  }

  // ========== Reusable toggle row component ==========
  component ToggleRow: CursorSurface {
    id: toggleRow
    required property string label
    required property string description
    required property bool checked
    required property string sectionName
    property bool enabled: true

    signal toggled()

    hasCursor: root.cursorActive && root.focusSection === sectionName
    foreground: root.bar.foreground
    fill: root.hoverFill

    implicitHeight: rowContent.implicitHeight + Style.spacing.rowPaddingX

    MouseArea {
      anchors.fill: parent
      hoverEnabled: true
      cursorShape: Qt.PointingHandCursor
      onContainsMouseChanged: if (containsMouse) {
        root.cursorActive = true
        root.focusSection = toggleRow.sectionName
      }
      onClicked: if (toggleRow.enabled) toggleRow.toggled()
    }

    Item {
      id: rowContent
      anchors.left: parent.left
      anchors.right: parent.right
      anchors.verticalCenter: parent.verticalCenter
      anchors.leftMargin: Style.space(10)
      anchors.rightMargin: Style.space(10)
      implicitHeight: Math.max(rowLabels.implicitHeight, rowSwitch.implicitHeight)

      Column {
        id: rowLabels
        anchors.left: parent.left
        anchors.right: rowSwitch.left
        anchors.rightMargin: Style.space(12)
        anchors.verticalCenter: parent.verticalCenter
        spacing: Style.space(1)

        Text {
          text: toggleRow.label
          color: root.bar.foreground
          font.family: root.bar.fontFamily
          font.pixelSize: Style.font.body
          elide: Text.ElideRight
          width: parent.width
        }

        Text {
          visible: toggleRow.description !== ""
          text: toggleRow.description
          color: Qt.darker(root.bar.foreground, 1.5)
          font.family: root.bar.fontFamily
          font.pixelSize: Style.font.caption
          elide: Text.ElideRight
          width: parent.width
          wrapMode: Text.WordWrap
        }
      }

      ToggleSwitch {
        id: rowSwitch
        anchors.right: parent.right
        anchors.verticalCenter: parent.verticalCenter
        checked: toggleRow.checked
        foreground: root.bar.foreground
        onToggled: if (toggleRow.enabled) toggleRow.toggled()
      }
    }
  }
}
